export const CITIES = [
    {
        latitude: 50.4547,
        longitude: 30.5238,
        daily: 'temperature_2m_max,temperature_2m_min,winddirection_10m_dominant',
        current_weather: true,
        timezone: 'Europe/Berlin',
        country: 'Ukraine',
        city: 'Kyiv',
        past_days: 7,
        forecast_days: 1,
    },
    {
        country: 'Ukraine',
        city: 'Dnipro',
        latitude: 48.4666,
        longitude: 35.0407,
        daily: 'temperature_2m_max,temperature_2m_min,winddirection_10m_dominant',
        current_weather: true,
        timezone: 'Europe/Berlin',
        past_days: 7,
        forecast_days: 1,
    },
    {
        country: 'Ukraine',
        city: 'Odessa',
        latitude: 46.4857,
        longitude: 30.7438,
        daily: 'temperature_2m_max,temperature_2m_min,winddirection_10m_dominant',
        current_weather: true,
        timezone: 'Europe/Berlin',
        past_days: 7,
        forecast_days: 1,
    },
    {
        country: 'England',
        city: 'London',
        latitude: 51.5085,
        longitude: -0.1257,
        daily: 'temperature_2m_max,temperature_2m_min,winddirection_10m_dominant',
        current_weather: true,
        timezone: 'Europe/London',
        past_days: 7,
        forecast_days: 1,
    },
    {
        country: 'Finland',
        city: 'Helsinki',
        latitude: 60.1695,
        longitude: 24.9354,
        daily: 'temperature_2m_max,temperature_2m_min,winddirection_10m_dominant',
        current_weather: true,
        timezone: 'Europe/Berlin',
        past_days: 7,
        forecast_days: 1,
    },
    {
        country: 'Italy',
        city: 'Venice',
        latitude: 45.4371,
        longitude: 12.3326,
        daily: 'temperature_2m_max,temperature_2m_min,winddirection_10m_dominant',
        current_weather: true,
        timezone: 'Europe/Berlin',
        past_days: 7,
        forecast_days: 1,
    },
    {
        country: 'Luxembourg',
        city: 'Luxembourg',
        latitude: 49.75,
        longitude: 6.1667,
        daily: 'temperature_2m_max,temperature_2m_min,winddirection_10m_dominant',
        current_weather: true,
        timezone: 'Europe/Berlin',
        past_days: 7,
        forecast_days: 1,
    },
    {
        country: 'Nederland',
        city: 'Amsterdam',
        latitude: 52.374,
        longitude: 4.8897,
        daily: 'temperature_2m_max,temperature_2m_min,winddirection_10m_dominant',
        current_weather: true,
        timezone: 'Europe/Berlin',
        past_days: 7,
        forecast_days: 1,
    },
];